-- 코드를 입력하세요
WITH RECURSIVE TIME AS
(
    SELECT 0 AS H
    UNION ALL
    SELECT h + 1 FROM TIME
    WHERE h < 23
)
SELECT T.H AS HOUR, COALESCE(COUNT(O.ANIMAL_ID), 0) AS COUNT
FROM TIME T LEFT JOIN ANIMAL_OUTS O
ON HOUR(O.DATETIME) = T.H
GROUP BY T.H
ORDER BY T.H