WITH RANKING AS
(
    SELECT MEMBER_ID, RANK() OVER(ORDER BY NUM DESC) AS RANKING
    FROM (
        SELECT MEMBER_ID, COUNT(MEMBER_ID) AS NUM
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    )A             
)
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M LEFT JOIN REST_REVIEW R
USING (MEMBER_ID)
WHERE MEMBER_ID = ANY (
                    SELECT MEMBER_ID
                    FROM RANKING
                    WHERE RANKING = 1
                  )
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT